//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3625
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSioex.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSioex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    xmlns:s=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///    &lt;s:String x:Key=&quot;account&quot;&gt;Account&lt;/s:String&gt;
        ///    &lt;s:String x:Key=&quot;password&quot;&gt;Password&lt;/s:String&gt;
        ///    &lt;s:String x:Key=&quot;search_newnode&quot;&gt;Search new node&lt;/s:String&gt;
        ///    &lt;s:String x:Key=&quot;waitpack&quot;&gt;Wait Packer Response&lt;/s:String&gt;
        ///    &lt;s:String x:Key=&quot;search_node&quot;&gt;Search node&lt;/s:String&gt;
        ///    &lt;s:String x:Key=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_US {
            get {
                return ResourceManager.GetString("en_US", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap en_US1 {
            get {
                object obj = ResourceManager.GetObject("en_US1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] MAIN {
            get {
                object obj = ResourceManager.GetObject("MAIN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;NodeDefine&gt;
        ///  &lt;reg&gt;
        ///    &lt;size&gt;8&lt;/size&gt;
        ///    &lt;name&gt;addr&lt;/name&gt;
        ///    &lt;offset&gt;0&lt;/offset&gt;
        ///    &lt;rw&gt;r&lt;/rw&gt;
        ///    &lt;update&gt;i&lt;/update&gt;
        ///  &lt;/reg&gt;
        ///  &lt;reg&gt;
        ///    &lt;size&gt;8&lt;/size&gt;
        ///    &lt;name&gt;board_id&lt;/name&gt;
        ///    &lt;offset&gt;1&lt;/offset&gt;
        ///    &lt;rw&gt;r&lt;/rw&gt;
        ///    &lt;update&gt;i&lt;/update&gt;
        ///  &lt;/reg&gt;
        ///  &lt;reg&gt;
        ///    &lt;size&gt;8&lt;/size&gt;
        ///    &lt;name&gt;baudrate&lt;/name&gt;
        ///    &lt;offset&gt;2&lt;/offset&gt;
        ///    &lt;rw&gt;r&lt;/rw&gt;
        ///    &lt;update&gt;i&lt;/update&gt;
        ///  &lt;/reg&gt;
        ///  &lt;reg&gt;
        ///    &lt;size&gt;16&lt;/size&gt;
        ///    &lt;name&gt;poise_weight_gram0&lt;/name&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string node_define {
            get {
                return ResourceManager.GetString("node_define", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ret1 {
            get {
                object obj = ResourceManager.GetObject("ret1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ret2 {
            get {
                object obj = ResourceManager.GetObject("ret2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    xmlns:s=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///    &lt;s:String x:Key=&quot;account&quot;&gt;帐号&lt;/s:String&gt;
        ///    &lt;s:String x:Key=&quot;password&quot;&gt;密码&lt;/s:String&gt;
        ///    &lt;s:String x:Key=&quot;search_newnode&quot;&gt;搜索新加斗&lt;/s:String&gt;
        ///    &lt;s:String x:Key=&quot;waitpack&quot;&gt;等待包装机响应&lt;/s:String&gt;
        ///    &lt;s:String x:Key=&quot;search_node&quot;&gt;搜索斗&lt;/s:String&gt;
        ///    &lt;s:String x:Key=&quot;auto_amp&quot;&gt;自动振幅调节&lt;/s:String&gt;
        ///    &lt;s:String [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zh_CN {
            get {
                return ResourceManager.GetString("zh_CN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap zh_CN1 {
            get {
                object obj = ResourceManager.GetObject("zh_CN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
