// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "rtestchartctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CRtestchartctrl1

IMPLEMENT_DYNCREATE(CRtestchartctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CRtestchartctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CRtestchartctrl1 operations
